; ========================================================
; * || Zombie Crown XP Mode - Modes accesses flags || *
; ========================================================

; ---------------------------------
; Access flags
; ---------------------------------
; a - access to menu  
; b - model
; c - zombie
; d - human
; e - respawn
; f - nemesis
; g - survivor
; h - assassin
; i - sniper
; j - genesys
; k - flamer
; l - oberon
; m - zadoc
; n - dragon
; o - nighter
; p - multi-infection
; q - swarm
; r - plague
; s - LNJ
; t - guardians
; u - weapons menu
; v - weapons menu
; w - weapons menu
; x - event
; y - no limit 
; z - on / off mode

; ---------------------------------
; Login flags
; ---------------------------------
; a - password
; e - no password

; ---------------------------------
; Accesses
; ---------------------------------
;"name" "password" "abcdefghijklmnopqrstuvwxyz" "a"

;------------
; Founder - abcdefghijklmnopqrstuvwxyz
;------------

"sus" "123" "abcdefghijklmnopqrstuvwxyz" "a"

;------------
; Owner (cu donatie) - abcdefghijlkmopqrstuvwx
;------------


;------------
; Co-Owner (cu donatie) - abcdefghijklmnopqrs
;------------


;-----------
; Elder (cu donatie) - abcdefghipqrs
; ----------


;-----------
; De la Moderator in sus - bcdefghipq
;-----------


; ----------
; Administrator - bcdp
;-----------


;-----------
; Helper - b
;----------


"sus" "123" "b" "e"
