; ======================================================
; * || Zombie Crown XP Mode - Human Classes File || *
; ======================================================

[Retros]
NAME = Retros
INFO = Balanced
MODELS = zc_model_human
HEALTH = 200
SPEED = 350
GRAVITY = 1.00
LEVEL = 1

[Poratri]
NAME = Poratri
INFO = 600 HP + Speed
MODELS = zc_model_human
HEALTH = 600
SPEED = 400
GRAVITY = 0.80
LEVEL = 1

[Lemow]
NAME = Lemow
INFO = High Jump
MODELS = zc_model_human
HEALTH = 300
SPEED = 350
GRAVITY = 0.50
LEVEL = 1

[Iceman]
NAME = Iceman
INFO = Free 5x frost grenades
MODELS = zc_model_human
HEALTH = 1200
SPEED = 400
GRAVITY = 0.85
LEVEL = 1

[Light Saber]
NAME = Light Saber
INFO = Free Lightsaber
MODELS = zc_model_human
HEALTH = 500
SPEED = 350
GRAVITY = 0.85
LEVEL = 1

[Spectral]
NAME = Spectral
INFO = 1/2 visibility
MODELS = zc_model_human
HEALTH = 450
SPEED = 350
GRAVITY = 0.85
LEVEL = 1

[Visioner]
NAME = Visioner
INFO = Free NightVision
MODELS = zc_model_human
HEALTH = 500
SPEED = 350
GRAVITY = 0.85
LEVEL = 1

[Wicked One]
NAME = Wicked One
INFO = Invulnerable 5s after inf
MODELS = zc_model_human
HEALTH = 400
SPEED = 430
GRAVITY = 0.91
LEVEL = 1

[Brizsat]
NAME = Brizsat
INFO = Can Leap
MODELS = zc_model_human
HEALTH = 400
SPEED = 330
GRAVITY = 0.91
LEVEL = 1

[Samurai]
NAME = Samurai
INFO = Fast knife
MODELS = zc_model_human
HEALTH = 800
SPEED = 370
GRAVITY = 0.79
LEVEL = 1

[Armorer]
NAME = Armorer
INFO = Balanced
MODELS = zc_model_human
HEALTH = 1200
SPEED = 340
GRAVITY = 0.85
LEVEL = 1

[Sharpshooter]
NAME = Sharpshooter
INFO = No Recoil
MODELS = zc_model_human
HEALTH = 500
SPEED = 340
GRAVITY = 0.87
LEVEL = 1

[Runner]
NAME = Runner
INFO = Speed
MODELS = zc_model_human
HEALTH = 900
SPEED = 650
GRAVITY = 0.75
LEVEL = 1

[Man of Dispair]
NAME = Man of Dispair
INFO = +15% DMG
MODELS = zc_model_human
HEALTH = 1100
SPEED = 400
GRAVITY = 0.69
LEVEL = 1

[Medic]
NAME = Medic
INFO = 1 antidote
MODELS = zc_model_human
HEALTH = 1400
SPEED = 450
GRAVITY = 0.69
LEVEL = 1

[Wiseman]
NAME = Wiseman
INFO = Shotgun + Unlimited Clip
MODELS = zc_model_human
HEALTH = 1300
SPEED = 420
GRAVITY = 0.74
LEVEL = 1

[Robber]
NAME = Robber
INFO = +50 packs/kill
MODELS = zc_model_human
HEALTH = 1800
SPEED = 490
GRAVITY = 0.69
LEVEL = 1

[Jack]
NAME = Jack
INFO = Free CSO Weapon
MODELS = zc_model_human
HEALTH = 1700
SPEED = 380
GRAVITY = 0.80
LEVEL = 1

[Faster]
NAME = Faster
INFO = 2x points
MODELS = zc_model_human
HEALTH = 1800
SPEED = 480
GRAVITY = 0.80
LEVEL = 1

[Ravenous]
NAME = Ravenous
INFO = Create explosion ring - C
MODELS = zc_model_human
HEALTH = 2200
SPEED = 510
GRAVITY = 0.69
LEVEL = 1

[Mutant]
NAME = Mutant
INFO = Nemesis after infection - 10 se
MODELS = zc_model_human
HEALTH = 1900
SPEED = 480
GRAVITY = 0.69
LEVEL = 1

[Survivor]
NAME = Survivor
INFO = Last human survivor
MODELS = zc_model_human
HEALTH = 1900
SPEED = 500
GRAVITY = 0.69
LEVEL = 1

[Magician]
NAME = Magician
INFO = Create entangles - C
MODELS = zc_model_human
HEALTH = 2200
SPEED = 510
GRAVITY = 0.69
LEVEL = 1

[Leucocyt]
NAME = Leucocyt
INFO = Immune to infection grenade
MODELS = zc_model_human
HEALTH = 2200
SPEED = 510
GRAVITY = 0.69
LEVEL = 1

[Arnodelo]
NAME = Arnodelo
INFO = Freeze power - C
MODELS = zc_model_human
HEALTH = 2200
SPEED = 500
GRAVITY = 0.69
LEVEL = 1

[Trix]
NAME = Trix
INFO = Get +3 XP/kill
MODELS = zc_model_human
HEALTH = 1800
SPEED = 500
GRAVITY = 0.69
LEVEL = 1

[Zolo]
NAME = Zolo
INFO = Get +2 coins/kill
MODELS = zc_model_human
HEALTH = 2100
SPEED = 500
GRAVITY = 0.69
LEVEL = 1
