; ======================================================
; * || Zombie Crown XP Mode - Customization File || *
; ======================================================

; Any changes you make here will be automatically loaded at map start
; Note: No error parsing is done for this.
; Make sure you don't mistype anything.

[Access Flags]
ENABLE/DISABLE MOD = z
ADMIN MENU = c
ADMIN MENU 2 = c
ADMIN MENU 3 = c
START MODE INFECTION = c
START MODE NEMESIS = f
START MODE SURVIVOR = g
START MODE SNIPER = i
START MODE ASSASSIN = h
START MODE OBERON = l
START MODE DRAGON = n
START MODE NIGHTER = o
START MODE LNJ = s
START MODE GUARDIANS = t
START MODE GENESYS = j
START MODE FLAMER = k
START MODE ZADOC = m
START MODE SWARM = q
START MODE MULTI = p
START MODE PLAGUE = r
MAKE ZOMBIE = c
MAKE HUMAN = d
MAKE NEMESIS = f
MAKE SURVIVOR = g
MAKE GENESYS = j
MAKE FLAMER = k
MAKE ZADOC = m
MAKE SNIPER = i
MAKE OBERON = l
MAKE DRAGON = n
MAKE NIGHTER = o
MAKE ASSASSIN = h
RESPAWN PLAYERS = e
ADMIN MODELS = b

[Player Models] (randomly chosen if more than one)
NEMESIS = zc_model_nemesis
SURVIVOR = zc_model_modes
ADMIN ZOMBIE = zc_model_admin
ADMIN HUMAN = zc_model_admin
VIP HUMAN = zc_model_modes
SNIPER = zc_model_modes
FLAMER = zc_model_modes
ZADOC = zc_model_modes
ASSASSIN = zc_oldschool_assassin
OBERON = zc_model_oberon
DRAGON = zc_model_dragon
NIGHTER = zc_model_nighter
NCHILD = zc_model_nchildren
GENESYS = zc_model_genesys
EVIL = zc_model_bigevil
HERO = zc_model_modes

; If you don't want people using altered player models, enable the following.
; 1 = Bounds Check (model's geometry must fit in the same bbox)
; 2 = CRC Check (file on client must exactly match server's file)
FORCE CONSISTENCY = 0

; By default, zombie models are class specific. You can edit them separately in your zp_zombieclasses.ini
; If, however, you want all zombies to use the same models regardless of class, you can enable this
; setting and add your global zombie models to the "ZOMBIE" line.
SAME MODELS FOR ALL = 0
ZOMBIE = zombie_source
HUMAN = arctic

[Weapon Models]
V_KNIFE HUMAN = models/zombie_crown/v_knife_hmn.mdl
V_KNIFE NEMESIS = models/zombie_crown/v_claws_z6.mdl
V_XM1014 SURVIVOR = models/v_xm1014.mdl
V_GRENADE INFECT = models/v_hegrenade.mdl
P_GRENADE INFECT = models/p_hegrenade.mdl
W_GRENADE INFECT = models/w_hegrenade.mdl
V_GRENADE FIRE = models/v_hegrenade.mdl
P_GRENADE FIRE = models/p_hegrenade.mdl
W_GRENADE FIRE = models/w_hegrenade.mdl
V_GRENADE FROST = models/v_smokegrenade.mdl
P_GRENADE FROST = models/p_smokegrenade.mdl
W_GRENADE FROST = models/w_smokegrenade.mdl
V_GRENADE EXPLOSION = models/v_flashbang.mdl
P_GRENADE EXPLOSION = models/p_flashbang.mdl
W_GRENADE EXPLOSION = models/w_flashbang.mdl
V_KNIFE ADMIN HUMAN = models/zombie_crown/v_knife_hmn.mdl
V_KNIFE ADMIN ZOMBIE = models/zombie_crown/v_knife_hmn.mdl
V_AWP SNIPER = models/v_awp1.mdl
V_WEAPON FLAMER = models/zombie_crown/v_weapon_flamer.mdl
P_WEAPON FLAMER = models/zombie_crown/p_weapon_flamer.mdl
V_KNIFE ZADOC = models/zombie_crown/v_zadoc_is.mdl
P_KNIFE ZADOC = models/zombie_crown/p_zadoc_is.mdl
V_KNIFE ASSASSIN = models/zombie_crown/v_claws_z2.mdl
V_KNIFE OBERON = models/zombie_crown/v_knife_oberon.mdl
V_KNIFE DRAGON = models/zombie_crown/v_claws_z6.mdl
V_KNIFE NIGHTER = models/zombie_crown/v_claws_z4.mdl
V_KNIFE NCHILD = models/zombie_crown/v_claws_z6.mdl
V_KNIFE GENESYS = models/zombie_crown/v_claws_z2.mdl
V_KNIFE EVIL = models/zombie_crown/v_claws_z3.mdl

[Grenade Sprites]
TRAIL = sprites/laserbeam.spr
RING = sprites/shockwave.spr
FIRE = sprites/flame.spr
SMOKE = sprites/black_smoke3.spr
GLASS = models/glassgibs.mdl

[Sounds] (randomly chosen if more than one)
WIN ZOMBIES = zombie_crown/zc_sound_zwin.wav
WIN HUMANS = zombie_crown/zc_sound_hwin.wav
WIN NO ONE = zombie_crown/zc_sound_zwin.wav
ZOMBIE INFECT = zombie_crown/zc_sound_infect1.wav , zombie_crown/zc_sound_infect2.wav
ZOMBIE PAIN = zombie_crown/zc_sound_hurt1.wav , zombie_crown/zc_sound_hurt2.wav , zombie_crown/zc_sound_hurt3.wav , zombie_crown/zc_sound_hurt4.wav
NEMESIS PAIN = zombie_crown/zc_sound_monsterhurt1.wav , zombie_crown/zc_sound_monsterhurt2.wav , zombie_crown/zc_sound_monsterhurt3.wav
ASSASSIN PAIN = zombie_crown/zc_sound_monsterhurt1.wav , zombie_crown/zc_sound_monsterhurt2.wav , zombie_crown/zc_sound_monsterhurt3.wav
OBERON PAIN = zombie_crown/zc_sound_monsterhurt1.wav , zombie_crown/zc_sound_monsterhurt2.wav , zombie_crown/zc_sound_monsterhurt3.wav
DRAGON PAIN = zombie_crown/zc_sound_monsterhurt1.wav , zombie_crown/zc_sound_monsterhurt2.wav , zombie_crown/zc_sound_monsterhurt3.wav
NIGHTER PAIN = zombie_crown/zc_sound_monsterhurt1.wav , zombie_crown/zc_sound_monsterhurt2.wav , zombie_crown/zc_sound_monsterhurt3.wav
GENESYS PAIN = zombie_crown/zc_sound_monsterhurt1.wav , zombie_crown/zc_sound_monsterhurt2.wav , zombie_crown/zc_sound_monsterhurt3.wav
EVIL PAIN = zombie_crown/zc_sound_monsterhurt1.wav , zombie_crown/zc_sound_monsterhurt2.wav , zombie_crown/zc_sound_monsterhurt3.wav
ZOMBIE DIE = zombie_crown/zc_sound_death1.wav , zombie_crown/zc_sound_death2.wav , zombie_crown/zc_sound_death3.wav
ZOMBIE FALL = zombie_crown/zc_sound_idle2.wav
ZOMBIE MISS SLASH = weapons/knife_slash1.wav , weapons/knife_slash2.wav
ZOMBIE MISS WALL = weapons/knife_hitwall1.wav
ZOMBIE HIT NORMAL = weapons/knife_hit1.wav , weapons/knife_hit2.wav , weapons/knife_hit3.wav , weapons/knife_hit4.wav
ZOMBIE HIT STAB = weapons/knife_stab.wav
ZOMBIE IDLE = zombie_crown/zc_sound_idle1.wav , zombie_crown/zc_sound_idle2.wav
ZOMBIE IDLE LAST = zombie_crown/zc_sound_idle1.wav , zombie_crown/zc_sound_idle2.wav
GRENADE INFECT EXPLODE = zombie_crown/zc_sound_grenade1.wav , zombie_crown/zc_sound_grenade2.wav
GRENADE INFECT PLAYER = zombie_crown/zc_sound_infect1.wav , zombie_crown/zc_sound_infect2.wav
GRENADE FIRE EXPLODE = zombie_crown/zc_sound_grenade1.wav , zombie_crown/zc_sound_grenade2.wav
GRENADE FIRE PLAYER = zombie_crown/zc_sound_burn1.wav , zombie_crown/zc_sound_burn2.wav
GRENADE FROST EXPLODE = zombie_crown/zc_sound_grenade1.wav , zombie_crown/zc_sound_grenade2.wav
GRENADE FROST PLAYER = warcraft3/impalehit.wav
GRENADE FROST BREAK = warcraft3/impalelaunch1.wav
GRENADE EXPLOSION = items/nvg_on.wav
ZOMBIE MADNESS = zombie_crown/zc_sound_madness.wav
ANTIDOTE = zombie_crown/zc_sound_coming1.wav , zombie_crown/zc_sound_coming2.wav
THUNDER = zombie_crown/zc_sound_coming1.wav , zombie_crown/zc_sound_coming2.wav
ROUND NEMESIS = zombie_crown/zc_sound_startmode1.wav
ROUND SURVIVOR = zombie_crown/zc_sound_startmode2.wav
ROUND SNIPER = zombie_crown/zc_sound_startmode1.wav
ROUND ASSASSIN = zombie_crown/zc_sound_startmode2.wav
ROUND FLAMER = zombie_crown/zc_sound_startmode1.wav
ROUND ZADOC = zombie_crown/zc_sound_startmode2.wav
ROUND OBERON = zombie_crown/zc_sound_startmode1.wav
ROUND DRAGON = zombie_crown/zc_sound_startmode2.wav
ROUND NIGHTER = zombie_crown/zc_sound_startmode1.wav
ROUND GENESYS = zombie_crown/zc_sound_startmode2.wav
ROUND SWARM = zombie_crown/zc_sound_startmode1.wav
ROUND MULTI = zombie_crown/zc_sound_startmode2.wav
ROUND PLAGUE = zombie_crown/zc_sound_startmode1.wav
ROUND LNJ = zombie_crown/zc_sound_startmode2.wav
ROUND GUARDIANS = zombie_crown/zc_sound_startmode1.wav

[Ambience Sounds] (randomly chosen if more than one) (only .wav and .mp3 formats supported) (duration is in seconds)
INFECTION ENABLE = 1
INFECTION SOUNDS = zombie_crown/zc_sound_ambience1.mp3
INFECTION DURATIONS = 115
NEMESIS ENABLE = 1
NEMESIS SOUNDS = zombie_crown/zc_sound_ambience2.mp3
NEMESIS DURATIONS = 33
SURVIVOR ENABLE = 1
SURVIVOR SOUNDS = zombie_crown/zc_sound_ambience3.mp3
SURVIVOR DURATIONS = 46
SNIPER ENABLE = 1
SNIPER SOUNDS = zombie_crown/zc_sound_ambience3.mp3
SNIPER DURATIONS = 46
FLAMER ENABLE = 1
FLAMER SOUNDS = zombie_crown/zc_sound_ambience2.mp3
FLAMER DURATIONS = 33
ASSASSIN ENABLE = 1
ASSASSIN SOUNDS = zombie_crown/zc_sound_ambience3.mp3
ASSASSIN DURATIONS = 46
GENESYS ENABLE = 1
GENESYS SOUNDS = zombie_crown/zc_sound_ambience1.mp3
GENESYS DURATIONS = 136
OBERON ENABLE = 1
OBERON SOUNDS = zombie_crown/zc_sound_ambience2.mp3
OBERON DURATIONS = 33
DRAGON ENABLE = 1
DRAGON SOUNDS = zombie_crown/zc_sound_ambience1.mp3
DRAGON DURATIONS = 136
NIGHTER ENABLE = 1
NIGHTER SOUNDS = zombie_crown/zc_sound_ambience2.mp3
NIGHTER DURATIONS = 33
ZADOC ENABLE = 1
ZADOC SOUNDS = zombie_crown/zc_sound_ambience1.mp3
ZADOC DURATIONS = 136
SWARM ENABLE = 1
SWARM SOUNDS = zombie_crown/zc_sound_ambience2.mp3
SWARM DURATIONS = 33
PLAGUE ENABLE = 1
PLAGUE SOUNDS = zombie_crown/zc_sound_ambience2.mp3
PLAGUE DURATIONS = 33
LNJ ENABLE = 1
LNJ SOUNDS = zombie_crown/zc_sound_ambience3.mp3
LNJ DURATIONS = 46
GUARDIANS ENABLE = 1
GUARDIANS SOUNDS = zombie_crown/zc_sound_ambience3.mp3
GUARDIANS DURATIONS = 46

[Buy Menu Weapons]
PRIMARY = weapon_m4a1 , weapon_mp5navy , weapon_ak47 , weapon_aug , weapon_galil , weapon_m3 , weapon_famas
SECONDARY = weapon_elite , weapon_glock18 , weapon_usp , weapon_deagle
ADDITIONAL ITEMS = weapon_hegrenade , weapon_flashbang , weapon_smokegrenade

[Extra Items: Weapons and their costs]
NAMES = Napalm Nade , Frost Nade , Explosion , AWP Magnum Sniper , M249 Para Machinegun , SG550 Auto-Sniper , G3SG1 Auto-Sniper
ITEMS = weapon_hegrenade , weapon_flashbang , weapon_smokegrenade , weapon_awp , weapon_m249 , weapon_sg550 , weapon_g3sg1
COSTS = 6 , 6 , 6 , 8 , 10 , 12 , 12

[Hard Coded Items Costs]
NIGHT VISION = 6
CUSTOM NVISION = 15
ANTIDOTE = 40
ZOMBIE MADNESS = 30
INFECTION BOMB = 70

[Weather Effects]
RAIN = 0
SNOW = 0
FOG = 0
FOG DENSITY = 0.00086
FOG COLOR = 121 121 121

[Custom Skies] (randomly chosen if more than one)
ENABLE = 1
SKY NAMES = space

[Zombie Decals] (for bloodstains/footsteps)
DECALS = 99 , 107 , 108 , 184 , 185 , 186 , 187 , 188 , 189

[Knockback Power for Weapons] (use -1.0 to disable knockback power for the weapon)
P228 = 2.4
SCOUT = 6.5
XM1014 = 8.0
MAC10 = 2.3
AUG = 5.0
ELITE = 2.4
FIVESEVEN = 2.0
UMP45 = 2.4
SG550 = 5.3
GALIL = 5.5
FAMAS = 5.5
USP = 2.2
GLOCK18 = 2.0
AWP = 10.0
MP5NAVY = 2.5
M249 = 5.2
M3 = 8.0
M4A1 = 5.0
TMP = 2.4
G3SG1 = 6.5
DEAGLE = 5.3
SG552 = 5.0
AK47 = 6.0
P90 = 2.0

[Objective Entities] (and anything that would affect gameplay that needs to be removed)
CLASSNAMES = func_bomb_target , info_bomb_target , info_vip_start , func_vip_safetyzone , func_escapezone , hostage_entity , monster_scientist , func_hostage_rescue , info_hostage_rescue , env_fog , env_rain , env_snow , item_longjump , func_vehicle

[SVC_BAD Prevention] (if you experience *many* SVC_BAD kicks, try one of the following)
; A. Increase the delay between model changes here (in 0.1 increments until the kicks are gone)
MODELCHANGE DELAY = 0.2
; B. If you still get recurring kicks, try enabling this setting: (experimental!)
HANDLE MODELS ON SEPARATE ENT = 0

; If you want your models to have accurate hitboxes, try enabling this.
; Note: make sure your models don't have messed up hitboxes, otherwise
; this setting might cause your server insane cpu usage and lag!
SET MODELINDEX OFFSET = 0