; ===================================================
; * || Zombie Crown XP Mode - Items List File || *
; ===================================================

[Strip Bomb]
NAME = Strip Bomb
COST = 60
TEAMS = ZOMBIE
REST_TYPE = 2
REST_LIMIT = 10

[Anti-Infection Armor]
NAME = Anti-Infection Armor
COST = 20
TEAMS = HUMAN
REST_TYPE = 1
REST_LIMIT = 5

[Tryder]
NAME = Tryder
COST = 110
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 3

[Unlimited Clip]
NAME = Unlimited Clip
COST = 25
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[Unlimited Clip - 1 map]
NAME = Unlimited Clip - 1 map
COST = 125
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[No Recoil]
NAME = No Recoil
COST = 20
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[Jetpack + Bazooka]
NAME = Jetpack + Bazooka
COST = 100
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 7

[Knife Blink]
NAME = Knife Blink
COST = 30
TEAMS = ZOMBIE
REST_TYPE = 1
REST_LIMIT = 15

[M16 Weapon]
NAME = M16 Weapon
COST = 350
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[Gas-Mask]
NAME = Gas-Mask
COST = 60
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 3

[Tripmine]
NAME = Tripmine
COST = 15
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[TMPDragon - 1 map]
NAME = TMPDragon - 1 map
COST = 230
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[HeavyZG]
NAME = HeavyZG
COST = 102
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 2

[Golden Deagle]
NAME = Golden Deagle
COST = 200
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 2

[Bomb-Mask]
NAME = Bomb-Mask
COST = 150
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 3

[Super-Mask]
NAME = Super-Mask
COST = 200
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 2

[Blade Impact]
NAME = Blade Impact
COST = 30
TEAMS = ZOMBIE
REST_TYPE = 2
REST_LIMIT = 5

[Dual Infinity]
NAME = Dual Infinity
COST = 100
TEAMS = HUMAN
REST_TYPE = 2
REST_LIMIT = 2

[CV-47 60R]
NAME = CV-47 60R
COST = 100
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Golden Ak47]
NAME = Golden Ak47
COST = 150
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[AUG CROW]
NAME = AUG CROW
COST = 150
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Golden AK47 VIP]
NAME = Golden AK47 VIP
COST = 300
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[M4A1 Dark Knight]
NAME = M4A1 Dark Knight
COST = 150
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[Silver AK47]
NAME = Silver AK47
COST = 100
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Diamond AK47]
NAME = Diamond AK47
COST = 800
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Golden AK47]
NAME = Golden AK47
COST = 150
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Golden M4A1]
NAME = Golden M4A1
COST = 300
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Diamond M4A1]
NAME = Diamond M4A1
COST = 800
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Silver M4A1]
NAME = Silver M4A1
COST = 100
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Minigun]
NAME = Minigun
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Brick Peace]
NAME = Brick Peace
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Air Burster]
NAME = Air Burster
COST = 5
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Rail Cannon]
NAME = Rail Cannon
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Plasma Gun]
NAME = Plasma Gun
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Poision Gun]
NAME = Poision Gun
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[M4a1 Dark Knight]
NAME = M4a1 Dark Knight
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Laser Minigun]
NAME = Laser Minigun
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Dual Uzi]
NAME = Dual Uzi
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Cyclone]
NAME = Cyclone
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Ak47 Paladin]
NAME = Ak47 Paladin
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Balrog 9]
NAME = Balrog 9
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[SF Tornado]
NAME = SF Tornado
COST = 10
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2

[Regeneration Armor]
NAME = Regeneration Armor
COST = 500
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 0

[Stun Refile]
NAME = Stun Refile
COST = 15
TEAMS = HUMAN
REST_TYPE = 0
REST_LIMIT = 2
