; =================================================
; * || Zombie Crown XP Mode - Settings File || *
; =================================================

; Any changes you make here will be automatically loaded at map start
; Note: No error parsing is done for this.
; Make sure you don't mistype anything.

[General]
ZP_DELAY = 9
ZP_THUNDERCLAP = 0.0
ZP_TRIGGERED_LIGHTS = 0
ZP_REMOVE_DOORS = 2 
ZP_BLOCKUSE_PUSHABLES = 1 
ZP_BLOCK_SUICIDE = 1 
ZP_RESPAWN_ON_WORLDSPAWN_KILL = 1
ZP_REMOVE_DROPPED = 10
ZP_BUY_CUSTOM = 1 
ZP_RANDOM_WEAPONS = 0 
ZP_ADMIN_MODELS_HUMAN = 1 
ZP_ADMIN_KNIFE_MODELS_HUMAN = 1
ZP_ADMIN_MODELS_ZOMBIE = 0
ZP_ADMIN_KNIFE_MODELS_ZOMBIE = 0 
ZP_ZOMBIE_CLASSES = 1 
ZP_HUMAN_CLASSES = 1
ZP_STARTING_AMMO_PACKS = 5000
ZP_KEEP_HEALTH_ON_DISCONNECT = 1 
ZP_HUMAN_SURVIVE = 1
ZP_COUNTDOWN = 1 
ZP_SHOW_HUD = 1
ZP_HUD_ALIVE_XPOS = 0.0
ZP_HUD_ALIVE_YPOS = 0.91
ZP_HUD_DEAD_XPOS = 0.37
ZP_HUD_DEAD_YPOS = 0.79
ZP_HUD_ALIVE_COLOR = 255 209 23
ZP_HUD_DEAD_COLOR = 255 255 255

[Deathmatch]
ZP_DEATHMATCH = 0
ZP_SPAWN_DELAY = 7.0
ZP_RESPAWN_ON_SUICIDE = 1
ZP_SPAWN_PROTECTION = 7 
ZP_RESPAWN_AFTER_LAST_HUMAN = 1 
ZP_INFECTION_ALLOW_RESPAWN = 1 
ZP_NEM_ALLOW_RESPAWN = 0 
ZP_SURV_ALLOW_RESPAWN = 0 
ZP_SNIPER_ALLOW_RESPAWN = 0 
ZP_ASSASSIN_ALLOW_RESPAWN = 0 
ZP_OBERON_ALLOW_RESPAWN = 0 
ZP_DRAGON_ALLOW_RESPAWN = 0 
ZP_NIGHTER_ALLOW_RESPAWN = 1 
ZP_SWARM_ALLOW_RESPAWN = 0 
ZP_PLAGUE_ALLOW_RESPAWN = 1 
ZP_FLAMER_ALLOW_RESPAWN = 0 
ZP_ZADOC_ALLOW_RESPAWN = 0 
ZP_RESPAWN_ZOMBIES = 1 
ZP_RESPAWN_HUMANS = 1 
ZP_RESPAWN_NEMESIS = 1 
ZP_RESPAWN_SURVIVORS = 1 
ZP_RESPAWN_SNIPERS = 0 
ZP_RESPAWN_FLAMERS = 0 
ZP_RESPAWN_ZADOCS = 0 
ZP_RESPAWN_ASSASSINS = 0 
ZP_RESPAWN_OBERONS = 0 
ZP_RESPAWN_DRAGONS = 0 
ZP_RESPAWN_NIGHTERS = 0 
ZP_RESPAWN_NCHILDS = 1
ZP_LNJ_ALLOW_RESPAWN = 1 
ZP_LNJ_RESPAWN_SURV = 1 
ZP_LNJ_RESPAWN_NEM = 1 
ZP_GUARDIANS_ALLOW_RESPAWN = 1 

[Extraitems]
ZP_EXTRA_ITEMS = 1 
ZP_EXTRA_WEAPONS = 1 
ZP_EXTRA_NVISION = 1 
ZP_EXTRA_CNVISION = 1 
ZP_EXTRA_ANTIDOTE = 1 
ZP_EXTRA_MADNESS = 1 
ZP_EXTRA_MADNESS_DURATION = 3.0
ZP_EXTRA_INFBOMB = 1

[Lights]
ZP_NVG_GIVE = 1
ZP_FLASH_CUSTOM = 0
ZP_FLASH_SIZE = 7
ZP_FLASH_SIZE_ASSASSIN = 7
ZP_FLASH_DRAIN = 1
ZP_FLASH_CHARGE = 5
ZP_FLASH_DISTANCE = 1000
ZP_FLASH_COLOR_R = 0
ZP_FLASH_COLOR_G = 0
ZP_FLASH_COLOR_B = 139
ZP_FLASH_COLOR_ASSASSIN_R = 139
ZP_FLASH_COLOR_ASSASSIN_G = 0
ZP_FLASH_COLOR_ASSASSIN_B = 0
ZP_FLASH_SHOW_ALL = 0

[Knockback]
ZP_KNOCKBACK = 1
ZP_KNOCKBACK_DAMAGE = 1 
ZP_KNOCKBACK_POWER = 1 
ZP_KNOCKBACK_ZVEL = 0 
ZP_KNOCKBACK_DUCKING = 0.25 
ZP_KNOCKBACK_DISTANCE = 500 
ZP_KNOCKBACK_NEMESIS = 0 
ZP_KNOCKBACK_ASSASSIN = 0 
ZP_KNOCKBACK_OBERON = 0
ZP_KNOCKBACK_DRAGON = 0 
ZP_KNOCKBACK_NIGHTER = 0

[Longjump]
ZP_LEAP_ZOMBIES = 2 
ZP_LEAP_ZOMBIES_FORCE = 400 
ZP_LEAP_ZOMBIES_HEIGHT = 300.0 
ZP_LEAP_ZOMBIES_COOLDOWN = 5.0 
ZP_LEAP_NEMESIS = 1 
ZP_LEAP_NEMESIS_FORCE = 750 
ZP_LEAP_NEMESIS_HEIGHT = 400.0 
ZP_LEAP_NEMESIS_COOLDOWN = 5.0 
ZP_LEAP_SURVIVOR = 1 
ZP_LEAP_SURVIVOR_FORCE = 500 
ZP_LEAP_SURVIVOR_HEIGHT = 300.0 
ZP_LEAP_SURVIVOR_COOLDOWN = 7.0 
ZP_LEAP_SNIPER = 1 
ZP_LEAP_SNIPER_FORCE = 500 
ZP_LEAP_SNIPER_HEIGHT = 300.0 
ZP_LEAP_SNIPER_COOLDOWN = 7.0 
ZP_LEAP_ASSASSIN = 1 
ZP_LEAP_ASSASSIN_FORCE = 700 
ZP_LEAP_ASSASSIN_HEIGHT = 450.0
ZP_LEAP_ASSASSIN_COOLDOWN = 5.0 
ZP_LEAP_OBERON = 1 
ZP_LEAP_OBERON_FORCE = 600 
ZP_LEAP_OBERON_HEIGHT = 350 
ZP_LEAP_OBERON_COOLDOWN = 5.0 
ZP_LEAP_DRAGON = 1 
ZP_LEAP_DRAGON_FORCE = 500 
ZP_LEAP_DRAGON_HEIGHT = 500 
ZP_LEAP_DRAGON_COOLDOWN = 1.0 
ZP_LEAP_NIGHTER = 1 
ZP_LEAP_NIGHTER_FORCE = 600 
ZP_LEAP_NIGHTER_HEIGHT = 500 
ZP_LEAP_NIGHTER_COOLDOWN = 5.0 
ZP_LEAP_FLAMER = 1 
ZP_LEAP_FLAMER_FORCE = 500 
ZP_LEAP_FLAMER_HEIGHT = 500 
ZP_LEAP_FLAMER_COOLDOWN = 7.0 
ZP_LEAP_ZADOC = 1 
ZP_LEAP_ZADOC_FORCE = 600 
ZP_LEAP_ZADOC_HEIGHT = 500 
ZP_LEAP_ZADOC_COOLDOWN = 7.0 

[Humans]
ZP_HUMAN_ARMOR_PROTECT = 1 
ZP_HUMAN_UNLIMITED_AMMO = 1
ZP_HUMAN_DAMAGE_REWARD = 300
ZP_HUMAN_FRAGS_FOR_KILL = 1 

[Grenades]
ZP_FIRE_GRENADES = 1 
ZP_FIRE_DURATION = 6.0
ZP_FIRE_DAMAGE = 15.0
ZP_FIRE_SLOWDOWN = 0.7 
ZP_FROST_GRENADES = 1 
ZP_FROST_DURATION = 5.0 
ZP_FROST_HIT = 1 
ZP_EXPLOSION_GRENADES = 1

[Zombies]
ZP_ZOMBIE_FIRST_HP = 2.0
ZP_ZOMBIE_ARMOR = 0.75 
ZP_ZOMBIE_HITZONES = 0 
ZP_ZOMBIE_INFECT_HEALTH = 250 
ZP_ZOMBIE_FOV = 0 
ZP_ZOMBIE_SILENT = 1 
ZP_ZOMBIE_PAINFREE = 2 
ZP_ZOMBIE_BLEEDING = 0 
ZP_ZOMBIE_INFECT_REWARD = 50 
ZP_ZOMBIE_FRAGS_FOR_INFECT = 2 
ZP_ZOMBIE_DAMAGE = 35.0

[Effects]
ZP_INFECTION_SCREENFADE = 0 
ZP_INFECTION_SCREENSHAKE = 0 
ZP_INFECTION_SPARKLE = 0 
ZP_INFECTION_TRACERS = 0 
ZP_INFECTION_PARTICLES = 0 
ZP_HUD_ICONS = 0 
ZP_SNIPER_FRAG_GORE = 1 
ZP_ASSASSIN_FRAG_GORE = 1 

[Nemesis]
ZP_NEM_ENABLED = 1 
ZP_NEM_CHANCE = 30 
ZP_NEM_MIN_PLAYERS = 3 
ZP_NEM_HEALTH = 100000 
ZP_NEM_BASE_HEALTH = 1 
ZP_NEM_SPEED = 700.0
ZP_NEM_GRAVITY = 0.55
ZP_NEM_DAMAGE = 1500 
ZP_NEM_GLOW = 1
ZP_NEM_AURA = 0
ZP_NEM_IGNORE_FRAGS = 0 
ZP_NEM_IGNORE_REWARDS = 0 

[Survivor]
ZP_SURV_ENABLED = 1 
ZP_SURV_CHANCE = 30 
ZP_SURV_MIN_PLAYERS = 3
ZP_SURV_HEALTH = 17000 
ZP_SURV_BASE_HEALTH = 1 
ZP_SURV_SPEED = 650.0 
ZP_SURV_GRAVITY = 0.6 
ZP_SURV_GLOW = 0
ZP_SURV_AURA = 0 
ZP_SURV_AURA_R = 102
ZP_SURV_AURA_G = 255
ZP_SURV_AURA_B = 255 
ZP_SURV_AURA_SIZE = 25 
ZP_SURV_PAINFREE = 1 
ZP_SURV_IGNORE_FRAGS = 0 
ZP_SURV_IGNORE_REWARDS = 0 
ZP_SURV_DAMAGE = 500.0
ZP_SURV_UNLIMITED_AMMO = 2 

[Swarm]
ZP_SWARM_ENABLED = 1 
ZP_SWARM_CHANCE = 25 
ZP_SWARM_MIN_PLAYERS = 0 

[Multiinfection]
ZP_MULTI_ENABLED = 1 
ZP_MULTI_CHANCE = 15 
ZP_MULTI_MIN_PLAYERS = 0 
ZP_MULTI_RATIO = 0.18 

[Plague]
ZP_PLAGUE_ENABLED = 1 
ZP_PLAGUE_CHANCE = 25 
ZP_PLAGUE_MIN_PLAYERS = 5 
ZP_PLAGUE_RATIO = 0.5 
ZP_PLAGUE_NEM_NUMBER = 3
ZP_PLAGUE_NEM_HP_MULTI = 1 
ZP_PLAGUE_SURV_NUMBER = 2 
ZP_PLAGUE_SURV_HP_MULTI = 4 

[Sniper]
ZP_SNIPER_ENABLED = 1 
ZP_SNIPER_CHANCE = 30 
ZP_SNIPER_MIN_PLAYERS = 3 
ZP_SNIPER_HEALTH = 8000 
ZP_SNIPER_BASE_HEALTH = 1 
ZP_SNIPER_SPEED = 650.0 
ZP_SNIPER_GRAVITY = 0.6
ZP_SNIPER_GLOW = 0
ZP_SNIPER_AURA = 0 
ZP_SNIPER_AURA_COLOR_R = 0 
ZP_SNIPER_AURA_COLOR_G = 200
ZP_SNIPER_AURA_COLOR_B = 0
ZP_SNIPER_AURA_SIZE = 25
ZP_SNIPER_PAINFREE = 1 
ZP_SNIPER_IGNORE_FRAGS = 0 
ZP_SNIPER_IGNORE_REWARDS = 0 
ZP_SNIPER_DAMAGE = 20000.0
ZP_SNIPER_UNLIMITED_AMMO = 2 

[Assassin]
ZP_ASSASSIN_ENABLED = 1 
ZP_ASSASSIN_CHANCE = 30 
ZP_ASSASSIN_MIN_PLAYERS = 3
ZP_ASSASSIN_HEALTH = 30000 
ZP_ASSASSIN_BASE_HEALTH = 1 
ZP_ASSASSIN_SPEED = 800.0 
ZP_ASSASSIN_GRAVITY = 0.55
ZP_ASSASSIN_DAMAGE = 1500.0 
ZP_ASSASSIN_GLOW = 0 
ZP_ASSASSIN_AURA = 0 
ZP_ASSASSIN_PAINFREE = 1 
ZP_ASSASSIN_IGNORE_FRAGS = 0 
ZP_ASSASSIN_IGNORE_REWARDS = 0 

[Flamer]
ZP_FLAMER_ENABLED = 1 
ZP_FLAMER_CHANCE = 30 
ZP_FLAMER_MIN_PLAYERS = 4
ZP_FLAMER_HEALTH = 8000 
ZP_FLAMER_SPEED = 650.0
ZP_FLAMER_GRAVITY = 0.6
ZP_FLAMER_GLOW = 0
ZP_FLAMER_AURA = 0
ZP_FLAMER_AURA_SIZE = 25 
ZP_FLAMER_AURA_COLOR_R = 246 
ZP_FLAMER_AURA_COLOR_G = 128
ZP_FLAMER_AURA_COLOR_B = 0 
ZP_FLAMER_DAMAGE = 500.0 
ZP_FLAMER_FIRE_DELAY = 0.1 
ZP_FLAMER_MAX_CLIP = 19900 
ZP_FLAMER_PAINFREE = 1  
ZP_FLAMER_IGNORE_FRAGS = 0 
ZP_FLAMER_IGNORE_REWARDS = 0 

[Zadoc]
ZP_ZADOC_ENABLED = 1 
ZP_ZADOC_CHANCE = 25 
ZP_ZADOC_MIN_PLAYERS = 3
ZP_ZADOC_HEALTH = 7000 
ZP_ZADOC_SPEED = 700.0 
ZP_ZADOC_GRAVITY = 0.6
ZP_ZADOC_GLOW = 0
ZP_ZADOC_AURA = 0
ZP_ZADOC_AURA_SIZE = 25
ZP_ZADOC_AURA_COLOR_R = 100 
ZP_ZADOC_AURA_COLOR_G = 0
ZP_ZADOC_AURA_COLOR_B = 100
ZP_ZADOC_DAMAGE = 7000.0 
ZP_ZADOC_PAINFREE = 1  
ZP_ZADOC_IGNORE_FRAGS = 0 
ZP_ZADOC_IGNORE_REWARDS = 0 
ZP_ZADOC_RADIUS = 300.0 
ZP_ZADOC_POWER_DELAY = 5 

[Genesys]
ZP_GENESYS_ENABLED = 1 
ZP_GENESYS_CHANCE = 25 
ZP_GENESYS_MIN_PLAYERS = 4
ZP_GENESYS_HEALTH = 25000 
ZP_GENESYS_DAMAGE = 500.0 
ZP_GENESYS_IGNORE_FRAGS = 0 
ZP_GENESYS_IGNORE_REWARDS = 0 
ZP_GENESYS_FLAMES_DMG = 800 
ZP_GENESYS_LOCUST_DELAY = 7

[Oberon]
ZP_OBERON_ENABLED = 1 
ZP_OBERON_CHANCE = 25 
ZP_OBERON_MIN_PLAYERS = 4
ZP_OBERON_HEALTH = 25000 
ZP_OBERON_BASE_HEALTH = 1 
ZP_OBERON_SPEED = 750.0 
ZP_OBERON_GRAVITY = 0.55 
ZP_OBERON_DAMAGE = 1000.0 
ZP_OBERON_GLOW = 1
ZP_OBERON_AURA = 0 
ZP_OBERON_PAINFREE = 1 
ZP_OBERON_IGNORE_FRAGS = 0 
ZP_OBERON_IGNORE_REWARDS = 0 
ZP_OBERON_HOLE_CD = 8
ZP_OBERON_BOMB_CD = 8 

[Dragon]
ZP_DRAGON_ENABLED = 1 
ZP_DRAGON_CHANCE = 25 
ZP_DRAGON_MIN_PLAYERS = 4
ZP_DRAGON_HEALTH = 25000 
ZP_DRAGON_BASE_HEALTH = 1 
ZP_DRAGON_SPEED = 700.0 
ZP_DRAGON_GRAVITY = 0.4 
ZP_DRAGON_DAMAGE = 1500.0 
ZP_DRAGON_GLOW = 1
ZP_DRAGON_AURA = 0 
ZP_DRAGON_PAINFREE = 1 
ZP_DRAGON_IGNORE_FRAGS = 0 
ZP_DRAGON_IGNORE_REWARDS = 0 
ZP_DRAGON_FROST_CD = 3.5 
ZP_DRAGON_FROST_DELAY = 3 

[Nighter]
ZP_NIGHTER_ENABLED = 1 
ZP_NIGHTER_CHANCE = 20 
ZP_NIGHTER_MIN_PLAYERS = 5
ZP_NIGHTER_HEALTH = 15000 
ZP_NIGHTER_BASE_HEALTH = 1 
ZP_NIGHTER_SPEED = 800.0 
ZP_NIGHTER_GRAVITY = 0.4 
ZP_NIGHTER_DAMAGE = 1000.0 
ZP_NIGHTER_GLOW = 0 
ZP_NIGHTER_AURA = 0 
ZP_NIGHTER_PAINFREE = 1 
ZP_NIGHTER_IGNORE_FRAGS = 0 
ZP_NIGHTER_IGNORE_REWARDS = 0 
ZP_NIGHTER_XP_REWARD = 1
ZP_NIGHTER_BLINK_CD = 10

[Nchild]
ZP_NCHILD_HEALTH = 2000 
ZP_NCHILD_SPEED = 800.0 
ZP_NCHILD_GRAVITY = 0.5
ZP_NCHILD_DAMAGE = 500.0 
ZP_NCHILD_XP_TO_NIGHTER = 1
ZP_NCHILD_PACKS_TO_NIGHTER = 100
ZP_NCHILD_COINS_TO_NIGHTER = 10

[Lnj]
ZP_LNJ_ENABLED = 1 
ZP_LNJ_CHANCE = 25 
ZP_LNJ_MIN_PLAYERS = 3
ZP_LNJ_NEM_HP_MULTI = 0.5 
ZP_LNJ_SURV_HP_MULTI = 3 
ZP_LNJ_RATIO = 0.5

[Guardians]
ZP_GUARDIANS_ENABLED = 1 
ZP_GUARDIANS_CHANCE = 25 
ZP_GUARDIANS_MIN_PLAYERS = 5
ZP_EVIL_HEALTH = 20000 
ZP_EVIL_SPEED = 750.0 
ZP_EVIL_GRAVITY = 0.5
ZP_EVIL_DAMAGE = 900.0
ZP_KNOCKBACK_EVIL = 0.25
ZP_HERO_HEALTH = 1000 
ZP_HERO_SPEED = 600.0 
ZP_HERO_GRAVITY = 0.7
ZP_HERO_UNLIMITED_AMMO = 1

[Powers]
ZP_CHAIN_COOLDOWN = 15
ZP_BLINK_COOLDOWN = 7 
ZP_POWERS_PRICE_HP = 5
ZP_POWERS_PRICE_ARMOR = 5
ZP_POWERS_PRICE_SPEED = 5
ZP_POWERS_PRICE_ASPIRINE = 15
ZP_POWERS_PRICE_BLINK = 15
ZP_POWERS_PRICE_THUNDERBOLT = 10
ZP_POWERS_PRICE_WALLHANG = 5
ZP_POWERS_LEVELS_HP = 75
ZP_POWERS_LEVELS_ARMOR = 75
ZP_POWERS_LEVELS_SPEED = 50
ZP_POWERS_LEVELS_ASPIRINE = 20
ZP_POWERS_LEVELS_BLINK = 35
ZP_POWERS_LEVELS_THUNDERBOLT = 15
ZP_POWERS_LEVELS_WALLHANG = 30
ZP_POWERS_HP_RATE = 15
ZP_POWERS_ARMOR_RATE = 15
ZP_POWERS_SPEED_RATE = 10
ZP_POWERS_ASP_RATE = 20

[Vip]
ZP_VIP_JUMPS = 5
ZP_PLAYER_JUMPS = 2 
ZP_VIP_ARMOR = 300 
ZP_VIP_ARMOR_HAPPY = 75 
ZP_VIP_KILLAMMO = 100 
ZP_VIP_UNLIMITED_CLIP = 1 
ZP_VIP_NO_RECOIL = 1 
ZP_VIP_DAMAGE_REWARD = 100 
ZP_VIP_DAMAGE_INCREASE = 8 
ZP_VIP_BUY_TIME = 15
ZP_VIP_HOUR_INIT = 23
ZP_VIP_HOUR_END = 8
ZP_VIP_HUD_ENABLE = 1
ZP_VIP_HUD_XPOS = 0.005
ZP_VIP_HUD_YPOS = 0.03
ZP_VIP_HUD_COLOR = 0 255 0

[Coinshop]
ZP_COINS_MAX_MODES = 2 
ZP_COINS_PRICE_HP = 10
ZP_COINS_PRICE_INVISIBILITY1 = 10
ZP_COINS_PRICE_SHOTGUN = 1
ZP_COINS_PRICE_GRENADE = 3
ZP_COINS_PRICE_GODMODE = 85
ZP_COINS_PRICE_NOCLIP = 75
ZP_COINS_PRICE_INVISIBILITY2 = 20
ZP_COINS_PRICE_MODEL = 1000
ZP_COINS_PRICE_VIP = 2000
ZP_COINS_PRICE_SURVIVOR = 100
ZP_COINS_PRICE_NEMESIS = 100
ZP_COINS_PRICE_SNIPER = 150
ZP_COINS_PRICE_ASSASSIN = 100
ZP_COINS_PRICE_FLAMER = 50
ZP_COINS_PRICE_GENESYS = 50
ZP_COINS_PRICE_OBERON = 50
ZP_COINS_PRICE_DRAGON = 50
ZP_COINS_PRICE_ZADOC = 100
ZP_COINS_PRICE_NIGHTER = 115
ZP_COINS_PRICE_PLAGUE = 200
ZP_COINS_PRICE_SWARM = 50
ZP_COINS_PRICE_LNJ = 150
ZP_COINS_PRICE_GUARDIANS = 150
ZP_COINS_LIMIT_HP = 3
ZP_COINS_LIMIT_INV1 = 3
ZP_COINS_LIMIT_INV2 = 2
ZP_COINS_LIMIT_GODMODE = 1
ZP_COINS_LIMIT_NOCLIP = 1
ZP_COINS_LIMIT_SURVIVOR = 1
ZP_COINS_LIMIT_NEMESIS = 1
ZP_COINS_LIMIT_SNIPER = 1
ZP_COINS_LIMIT_ASSASSIN = 1
ZP_COINS_LIMIT_FLAMER = 1
ZP_COINS_LIMIT_GENESYS = 1
ZP_COINS_LIMIT_OBERON = 1
ZP_COINS_LIMIT_DRAGON = 1
ZP_COINS_LIMIT_ZADOC = 1
ZP_COINS_LIMIT_NIGHTER = 1
ZP_COINS_LIMIT_PLAGUE = 1
ZP_COINS_LIMIT_SWARM = 1
ZP_COINS_LIMIT_LNJ = 1
ZP_COINS_LIMIT_GUARDIANS = 1

[Steps]
ZP_LEVEL_MAX = 250
ZP_LEVEL_STEP = 2
ZP_XP_PLAYER_HUMAN = 1
ZP_XP_PLAYER_ZOMBIE = 1
ZP_XP_VIP_HUMAN = 2
ZP_XP_VIP_ZOMBIE = 2
ZP_POINTS_MINUTES = 1.5

[Others]
ZP_LOGCOMMANDS = 1
ZP_SHOW_ACTIVITY = 2