; ================================================
; * || Zombie Crown XP Mode - VIP accesses || *
; ================================================

; ---------------------------------
; Access flags
; ---------------------------------
; a - ammo reward, more frags
; b - multi-jump, nightvision
; c - unlimited clip, no-recoil
; d - damage, model
; e - items

; ---------------------------------
; Login Flags
; ---------------------------------
; a - password
; e - no password

; ---------------------------------
; Accounts
; ---------------------------------
;"name" "password" "abcde" "a"
"sus" "123" "abcde" "e"; Exp: m2d21y2025