; =====================================================
; * || Zombie Crown XP Mode - Game plugins file || *
; =====================================================

; ---------------------------------
; Base plugins
; ---------------------------------
zc_mode.amxx debug
zc_resetwpn.amxx debug
zc_supply.amxx debug
zc_coord.amxx debug
zc_crystal.amxx debug
zc_flash.amxx debug

; ---------------------------------
; Special guns
; ---------------------------------
zc_guillotine.amxx debug
zc_coilgun.amxx debug
zc_janus5.amxx debug
zc_cannon.amxx debug

; ---------------------------------
; Human classes plugin
; ---------------------------------
zc_humans.amxx debug

; ---------------------------------
; Zombie classes plugins
; ---------------------------------
1_classic.amxx debug
4_bunnyzm.amxx debug
8_houndeye.amxx debug
12_warlock.amxx debug
16_thermal.amxx debug
20_doom.amxx debug
24_lockers.amxx debug
28_camouflage.amxx debug
32_deimos.amxx debug
36_ghost.amxx debug
40_licker.amxx debug
44_hunterzm.amxx debug
48_tank.amxx debug
52_jumper.amxx debug
56_smoker.amxx debug
60_siren.amxx debug
64_blink.amxx debug
67_revenant.amxx debug
70_fleshpound.amxx debug
74_spitter.amxx debug
78_cereberus.amxx debug
82_suicide.amxx debug
86_crow.amxx debug
89_boomer.amxx debug
93_exec.amxx debug
97_irichol.amxx debug
100_bop.amxx debug

; ---------------------------------
; Extra-items plugins
; ---------------------------------
zc_harmor.amxx debug
zc_tryder.amxx debug
zc_unlimitedclip.amxx debug
zc_unlimitedclip_map.amxx debug
zc_norecoil.amxx debug
zc_jetpack.amxx debug
zc_knifeb.amxx debug
zc_m16.amxx debug
zc_gasmask.amxx debug
zc_stripbomb.amxx debug
zc_tripmine.amxx debug
zc_tmpdragon.amxx debug
zc_heavyzg.amxx debug
zc_gdeagle.amxx debug
zc_bombmask.amxx debug
zc_supermask.amxx debug
zc_bladeimpact.amxx debug
zc_dualinfinity.amxx debug
zc_silver_ak.amxx debug
zc_diamond_ak.amxx debug
zc_member_diamond_m4.amxx debug
zc_member_silver_m4.amxx debug
;zc_minigun.amxx debug
zc_brickpeace.amxx debug
zc_air_burster.amxx debug
zc_railcannon.amxx debug
zc_plasmagun.amxx debug
zc_poisiongun.amxx deubg
zc_m4a1darkknight.amxx debug
zc_lazerminigun.amxx debug
zc_dualuzi.amxx debug
zc_cyclone.amxx debug
zc_ak47_paladin.amxx debug
;zc_balrog9.amxx debug
zc_sf_tornado.amxx
zp_extra_regen_armor.amxx debug
ze_stun_rifle.amxx
zc_balrog5.amxx debug
zc_skull11.amxx debug
zc_thanatos7.amxx debug

; ---------------------------------
; VIP extra-items plugins
; ---------------------------------
zc_member_armor.amxx debug
zc_member_blindbmb.amxx debug
zc_member_killbmb.amxx debug
zc_member_at4cs.amxx debug
zc_member_ak47.amxx debug
zc_member_concbomb.amxx debug
zc_member_eth.amxx debug
zc_member_blaster.amxx debug
zc_member_gm4a1.amxx  debug
zc_member_plasma.amxx debug
zc_member_watergun.amxx debug
zc_member_janus11.amxx debug
zc_member_rustler.amxx debug
zc_member_gak47.amxx debug
zc_member_augcrow2.amxx debug

; ---------------------------------
; New function plugin
; ---------------------------------
zc_blockradio.amxx debug
bullet_damage.amxx debug
zc_get.amxx debug
zc_mission.amxx debug
zc_random_legend.amxx debug
zc_aiminfo.amxx debug


;zc_m4a1_knight.amxx debug