; ===============================================
; * || Zombie Crown XP Mode - Admins file || *
; ===============================================

;c - amx_kick | amx_nick | amx_ip | amx_ss | amx_removeannounce
;d - amx_ban | amx_banip | amx_addban | amx_unban | amx_last | amx_banmenu
;e - amx_slay | amx_slap | amx_slapmenu
;f - amx_map | amx_mapmenu
;i - amx_say | amx_chat | amx_psay | amx_tsay | amx_csay | amx_gag | amx_ungag
;j - amx_teammenu | amx_votemapmenu | amx_votemap | amx_votekick | amx_voteban | amx_vote | amx_cancelvote
;l - amx_reloadadmins | amx_speechmenu | amx_plugincmdmenu | amx_clcmdmenu | amx_reloadaccesses | amx_reloadvips | amx_reloadrn | amx_nume | amx_reloadtags

;m - amx_set_level | amx_sethp | amx_setspeed | amx_setarmor | amx_setblink | amx_setchain | amx_setwallh | amx_setaspirine | amx_setghost | amx_setdivine | amx_set_coins | amx_set_xp | amx_set_ampks | amx_set_points | amx_vip_bonus | zc_maker | zp_points_e_self | zp_coins_e_self | amx_addadmin | amx_rcon | amx_showrcon | amx_setlang | amx_cmdmenu | amx_cfgmenu
; amx_statscfgmenu | amx_statscfg | amx_cvarmenu | amx_pausecfg | amx_pausecfgmenu | amx_off | amx_on | amx_leave | amx_pause | amx_cvar | amx_plugins | amx_modules | amx_cfg | amx_plugincvarmenu

;n - amx_givebonus
;o - amx_givecanon | amx_givetdragon | amx_giveblaster | amx_giveat4cs | amx_giveethereal | amx_givenewcomen | amx_giveheavyzg | amx_givejetpack | amx_givejanus | amx_givegdeagle | amx_givegm4a1 | amx_givewatergun | amx_givepr | amx_givevulcanus | amx_giveak47long | amx_givepg
;p - amx_destroy
;q - amx_fuckoff | amx_pimpslap | amx_unfuckoff | amx_unpimpslap | amx_spank | amx_spin | amx_unspin
;t - zp_ammo_e_self
;z - amx_slot_password | amx_vipb_password | amx_vipc_password

; ---------------------------------
; Login flags
; ---------------------------------
; a - password
; b - clantag
; c - steam
; e - no password
; k - sensitive case (meNe not mene)

; ---------------------------------
; Accesses
; ---------------------------------

;-------------------
;Founder ---- abcdefghijklmnopqrstuvwxz
;-------------------

"sus" "123" "abcdefghijklmnopqrstuvwxz"

;-------------------
;Owner ---- abcdefghijklnpqrstuvwx
;-------------------

"sus" "123" "abcdefghijklnpqrstuvwx"

;-------------------
;Co-Owner ---- bcdefghijklnpqrstu
;-------------------

"sus" "123" "bcdefghijklnpqrstu"

;-------------------
;Elder ---- bcdefghijklnpqrs
;-------------------

"sus" "123" "bcdefghijklnpqrs"

;-------------------
;Semi-Elder ---- bcdefghijklprs
;-------------------

"sus" "123" "bcdefghijklprs"

;-------------------
;Moderator ---- bcdefghijklrs
;-------------------

"sus" "123" "bcdefghijklrs"

;-------------------
;Administrator ---- bcefghijklrs
;-------------------

"sus" "123" "bcefghijklrs"

;-------------------
;Helper ---- bceghijklrs
;-------------------

"sus" "123" "bceghijklrs"
