native zp_get_user_level(id)

/**
 * Sets a player's level count.
 *
 * @param id		Player index.
 * @param amount	Number of level added.
 */
native zp_set_user_level(id, amount)

/**
 * Returns a player's Total Power count.
 *
 * @param id		Player index.
 * @return		Number of coins owned.
 */
native zp_get_user_tpower(id)

/**
 * Returns a player's NextLevel count.
 *
 * @param id		Player index.
 * @return		Number of nextlevel xp owned.
 */
native zp_get_user_next(id)

